import type { Metadata } from "next";
import { Funnel_Display, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const funnel = Funnel_Display({
  subsets: ["latin"],
  weight : ["300","400","500" , "600","700","800"],
  variable: "--font-funnel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", funnel.className, "font-sans", geist.variable)}>
      <body className="min-h-full flex flex-col font-[var(--font-funnel)]">
        {children}
      </body>
    </html>
  );
}